In [27]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

In [28]:
tensor = torch.rand(7,7).to(device)

In [29]:
tensor

tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018],
        [0.9497, 0.6666, 0.9811, 0.0874, 0.0041, 0.1088, 0.1637],
        [0.7025, 0.6790, 0.9155, 0.2418, 0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524, 0.6057],
        [0.3725, 0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313]])

In [30]:
tensor2 = torch.rand(1, 7).to(device)
tensor2 = tensor2.T


In [31]:
torch.matmul(tensor , tensor2)

tensor([[1.0466],
        [1.0884],
        [0.9919],
        [0.6820],
        [0.9108],
        [1.0100],
        [0.8004]])

In [33]:
x = 1234
torch.manual_seed(x)

In [34]:
t1 = torch.rand(2, 3)
torch.manual_seed(x)
t2 = torch.rand(2, 3)

In [35]:
t1, t2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]))

In [36]:
res = torch.matmul(t1, t2.T)

In [37]:
res

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

In [39]:
torch.min(res), torch.max(res)

(tensor(0.2161), tensor(0.6287))

In [40]:
torch.argmax(res), torch.argmin(res)

(tensor(3), tensor(1))

In [53]:
t3 = torch.rand([1, 1, 1, 10], dtype=torch.float64)
t4 = t3.squeeze()

In [55]:
t3.shape, t4.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))